#!/usr/bin/env python
# coding: utf-8

# In[1]:


print("Hola mundo")



# In[2]:


nombre=input("Ingrese su nombre")
print("Hola",nombre)



# In[ ]:





# In[9]:


nombre=input("Ingrese su nombre y apellido")
edad=input("Ingrese su edad")
residencia=input("Ingrese su lugar de residencia")
print("Hola soy",nombre, "tengo", edad, "años y vivo en",residencia)


# In[3]:


radio=int(input("Ingrese el radio de un circulo"))
import math
area = math.pi * radio**2
print("El area del circulo es", area)


# In[13]:


segundos=int(input("Ingrese una cantidad de segundos"))
horas = segundos/3600
print(segundos,"segundos son",horas,"horas")


# In[15]:


numero=int(input("Ingrese un numero"))
print(numero *1)
print(numero *2)
print(numero* 3)
print(numero*4)
print(numero*5)
print(numero*6)
print(numero*7)
print(numero*8)
print(numero*9)
print(numero*10)


# In[25]:


altura=float(input("Ingrese su altura"))
peso= float(input("Ingrese su peso"))
imc = (peso/altura**2)
print("Su indice de masa corporal es",imc)


# In[27]:


T= float(input("Ingrese la temperatura en grados celsius"))
Farenheit= 9/5*(T)+32
print("La temperatura en grados Farenheit es", Farenheit)




# In[30]:


num1= float(input("Ingrese un numero"))
num2= float(input("Ingrese un numero"))
num3= float(input("Ingrese un numero"))
promedio= (num1+num2+num3)/3
print("El promedio es",promedio)


# In[ ]:




